# Generated by Django 3.2.4 on 2021-06-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parkmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrname', models.CharField(max_length=100)),
                ('usremail', models.EmailField(max_length=254)),
                ('usrnumber', models.IntegerField(blank=True, null=True)),
                ('usrdob', models.DateTimeField()),
            ],
        ),
    ]
